name: 'Setup'
description: 'Common setup for all build/test jobs'
inputs:
  conanprofile:
    description: 'Profile to use for conan install'
    required: true
    default: 'default'
runs:
  using: 'composite'
  steps:
  - name: Install python
    uses: actions/setup-python@v4
    with: { python-version: "3.10" }

  - name: Install build requirements
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install ninja-build
      pip3 install conan==1.59

  - name: Install conan dependencies
    shell: bash
    run: |
      conan config install https://github.com/dariusarnold/conan-profiles.git
      conan profile new --detect --force default
      conan profile update settings.compiler.libcxx=libstdc++11 default
      conan install . --build=missing -pr:b=${{ inputs.conanprofile }} -pr:h=${{ inputs.conanprofile }} \
        -c tools.system.package_manager:mode=install \
        -c tools.system.package_manager:sudo=True \
