name: continuous integration
run-name: Build with GCC
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: gb_devcontainer
          push: never
          runCmd: ./conan_build.sh
